version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio_recommender_system_v3
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  minio-init:
    image: minio/mc:latest
    container_name: minio_init_buckets_v3
    depends_on:
      minio:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/datasets --ignore-existing;
      mc anonymous set download myminio/datasets;
      echo 'Бакет datasets создан успешно';
      "
    volumes:
      - minio_data:/data

volumes:
  minio_data: